-- Phase A initial schema.
--
-- All per-user tables carry user_id from day one even though Phase A only
-- writes user_id = 1; this avoids a second migration when auth lands in
-- Phase B. Subjects still live in data/subjects.json for now and will move
-- into a `subjects` table in Phase C alongside Google sign-in.

CREATE TABLE IF NOT EXISTS users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         TEXT UNIQUE NOT NULL,
  display_name  TEXT,
  google_sub    TEXT UNIQUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Phase-A bootstrap row. Real users replace this in Phase B; the row stays
-- around as id=1 so anything seeded against it doesn't dangle.
INSERT INTO users (id, email, display_name)
VALUES (1, 'default@local', 'Default User')
ON CONFLICT (id) DO NOTHING;

-- IDENTITY sequence needs to be advanced past any manually-inserted ids,
-- otherwise the next auto-generated row tries to claim id=1 and conflicts.
SELECT setval(
  pg_get_serial_sequence('users', 'id'),
  GREATEST(1, (SELECT COALESCE(MAX(id), 1) FROM users))
);

CREATE TABLE IF NOT EXISTS seen_emails (
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  subject_id   TEXT NOT NULL,
  message_id   TEXT NOT NULL,
  processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, subject_id, message_id)
);

CREATE TABLE IF NOT EXISTS site_hashes (
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  subject_id   TEXT NOT NULL,
  source_url   TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  fetched_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, subject_id, source_url)
);

-- Phase D will drop this table once file downloads are removed. Kept now so
-- the existing pipeline keeps working through Phase A.
CREATE TABLE IF NOT EXISTS downloaded_files (
  user_id        INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  file_hash      TEXT NOT NULL,
  path           TEXT NOT NULL,
  downloaded_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, file_hash)
);

CREATE INDEX IF NOT EXISTS idx_downloaded_files_user_path
  ON downloaded_files(user_id, path);

CREATE TABLE IF NOT EXISTS synced_events (
  user_id        INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  event_id       TEXT NOT NULL,
  subject_id     TEXT NOT NULL,
  item_id        TEXT NOT NULL,
  last_synced_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, event_id)
);

CREATE INDEX IF NOT EXISTS idx_synced_events_user_subject
  ON synced_events(user_id, subject_id);

CREATE TABLE IF NOT EXISTS calendar_items (
  user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  event_id        TEXT NOT NULL,
  subject_id      TEXT NOT NULL,
  item_id         TEXT NOT NULL,
  kind            TEXT NOT NULL,
  summary         TEXT NOT NULL,
  description     TEXT NOT NULL DEFAULT '',
  start_iso       TEXT NOT NULL,
  end_iso         TEXT NOT NULL,
  room            TEXT,
  attachments     JSONB NOT NULL DEFAULT '[]'::jsonb,
  recurrence      JSONB,
  source_label    TEXT,
  last_synced_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, event_id)
);

CREATE INDEX IF NOT EXISTS idx_calendar_items_user_subject_start
  ON calendar_items(user_id, subject_id, start_iso);
CREATE INDEX IF NOT EXISTS idx_calendar_items_user_start
  ON calendar_items(user_id, start_iso);

CREATE TABLE IF NOT EXISTS user_settings (
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  key        TEXT NOT NULL,
  value      TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, key)
);

CREATE TABLE IF NOT EXISTS event_redirects (
  user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  subject_id      TEXT NOT NULL,
  item_id         TEXT NOT NULL,
  target_event_id TEXT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, subject_id, item_id)
);

CREATE TABLE IF NOT EXISTS whatsapp_messages (
  id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  phone       TEXT NOT NULL,
  role        TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  body        TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_user_phone_created
  ON whatsapp_messages(user_id, phone, created_at);
